version: "3"
services:
  vue-mqtt.local:
    build:
      context: ../
      dockerfile: ./local/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    tty: true
